LibaryManagementSystem/Controllers/BookController.cs
using CollegeWebsite.Data;
using CollegeWebsite.Models;
using DemoIntro.filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CollegeWebsite.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Authorize("Admin")]
        public async Task<IActionResult> Index(string sortOrder,string currentFilter,string searchString,int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AuthSortParm"] = sortOrder == "Authname" ? "Authname_desc" : "Authname";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }



            ViewData["CurrentFilter"] = searchString;

            var students = from s in _db.Book
                            select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.BookName.Contains(searchString)
                                        || s.AuthorName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.BookName);
                    break;
                case "Authname":
                    students = students.OrderBy(s => s.AuthorName);
                    break;
                case "Authname_desc":
                    students = students.OrderByDescending(s => s.AuthorName);
                    break;
                default:
                    students = students.OrderBy(s => s.BookName);
                    break;
            }
            int pageSize = 4;
            var temp = await PaginatedList<Book>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize);
            return View(temp);
            //return View(await students.AsNoTracking().ToListAsync());
            

            

            

        }


        //Get-Upsert
        public IActionResult Upsert(int? id)
        {
            Book book = new Book();

            if (id == null)
            {
                
                return View(book);
                
            }

            var temp = _db.Book.Find(id);

            if (temp == null)
            {
                return NotFound();
            }


            return View(temp);
        }

        //POST-Upsert

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize("Admin")]
        public async Task<IActionResult> Upsert(Book book)
        {
            if (ModelState.IsValid)
            {
                
                if (book.Id == 0)
                {
                    //Create
                    book.ISBN = Guid.NewGuid().ToString();
                    _db.Book.Add(book);

                }

                else
                {
                    //Update
                    //how is it tracking two instances
                    if (!book.Issued) 
                    { 
                        book.IssueDate = "";
                        book.IssuedStudentId = 0;
                        book.DueDate = "";


                    }
                    _db.Book.Update(book);

                }

                //why on updating the value need to be assigned again
                _db.SaveChanges();
                var students = from s in _db.Book
                               select s;
                var temp = await PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 4);
                var htmlx = Helper.RenderRazorViewToString(this, "_ViewAll",temp);
                //PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 3)



                return Json(new { isValid = true,html=  htmlx });
                //return RedirectToAction("Index");

            }

            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Upsert", book ) });

            // return View(Book);
        }



        //get delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Book.Find(id);
            //var obj = _db.Category.Find(id);

            //Product product = _db.Product.Find(id);  not efficient approach 
            //Eager Loading 
            ////////////////////////////////here i got a problemmmm
           // Product product = _db.Product.Include(u => u.Category).Include(u => u.ApplicationType).FirstOrDefault(u => u.Id == id);
            //above is eager loading

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        //POST-delete
        //????????????????????????????????????????????????????????????????????????????????????
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {

            var obj = _db.Book.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            



            _db.Book.Remove(obj);
            _db.SaveChanges();
            var students = from s in _db.Book
                           select s;
            var temp = await PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 4);
            var htmlx = Helper.RenderRazorViewToString(this, "_ViewAll", temp);
            //PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 3)



            return Json(new { isValid = true, html = htmlx });

            //return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", _db.Book.ToList()) });
            //return RedirectToAction("Index");



        }

        public async Task<IActionResult> Return(int? id)
        {
            var temp = _db.Book.Find(id);
            temp.DueDate = "";
            temp.Issued = false;
            temp.IssueDate = "";
            temp.IssuedStudentId = 0;

            _db.Book.Update(temp);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //get delete
        public IActionResult Issue(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Book.Find(id);
            

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        //POST-delete
        //????????????????????????????????????????????????????????????????????????????????????
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize("Admin")]
        public async Task<IActionResult> Issue(Book book)
        {
            if (ModelState.IsValid)
            {


                book.Issued = true;

                    _db.Book.Update(book);

                

                //why on updating the value need to be assigned again
                _db.SaveChanges();
                var students = from s in _db.Book
                               select s;
                var temp = await PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 4);
                var htmlx = Helper.RenderRazorViewToString(this, "_ViewAll", temp);
                //PaginatedList<Book>.CreateAsync(students.AsNoTracking(), 1, 3)



                return Json(new { isValid = true, html = htmlx });
                //return RedirectToAction("Index");

            }

            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Upsert", book) });

            // return View(Book);
        }




    }
}

LibaryManagementSystem/Controllers/LoginController.cs
using CollegeWebsite.Data;
using CollegeWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

public class LoginController : BaseController
{
    ApplicationDbContext db;
    public LoginController(ApplicationDbContext db)
    {
        this.db = db;
    }
    [HttpGet, AllowAnonymous]
    public IActionResult Index([FromQuery(Name = "returnurl")] string returnurl)
    {   
        TempData["returnurl"] = returnurl;
        return View();
    }

    [HttpPost, AllowAnonymous]
    public IActionResult LoginNow(User model, [FromQuery(Name = "returnurl")] String returnurl)
    {
        var admin = db.User.Where(x => x.UserName.Trim() == model.UserName.Trim() && x.Password == model.Password).FirstOrDefault();
        try
        {
            if (admin != null)
            {
                _ = CreateAuthenticationTicket(admin);
                // Show Success Message -"Welcome!"    
                // return RedirectToAction(nameof(ProfileController.CreateEditProfile), "Profile");
                //return RedirectToAction(nameof(HomeController.Privacy));

                if (TempData["returnurl"] != null)
                 {
                      this.Response.Redirect(TempData["returnurl"].ToString());
                     string[] values = TempData["returnurl"].ToString().Split("/");
                     return RedirectToAction(values[2],values[1]);
                 }

               
               
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //  Show Error Message- "Invalid Credentials."    
                return View("Index", model);
            }
        }
        catch (Exception ex)
        {
            //Show Error Message- ex.Message    
            return View("Index", model);
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Index");
    }
}

LibaryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CollegeWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CollegeWebsite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <!--
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
        -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.HasClaim("Role", "Admin") || !User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index"> Register </a>
                            </li>
                        }


                        @if (User.HasClaim("Role", "Admin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index"> Roles </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index"> Books </a>
                            </li>
                        }

                        @if (User.HasClaim("Role", "Student"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index"> Books Issued </a>
                            </li>


                        }

                        @if (!User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index"> Login </a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout"> Logout </a>
                            </li>



                        }






                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <!--<h5 class="modal-title"></h5>-->
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p></p>
                </div>
                
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CollegeWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibaryManagementSystem/Views/Shared/_ViewAll.cshtml
@model PaginatedList<CollegeWebsite.Models.Book>
<table class="table table-bordered table-striped table-dark" style="width:100%">
    <thead>
        <tr>

            <th scope="col">
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Book Name</a>


            </th>
            <th scope="col">
                <a asp-action="Index" asp-route-sortOrder="@ViewData["AuthSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Aurthor Name</a>

            </th>


            <th scope="col">
                ISBN
            </th>

            <th scope="col">
                Student Id
            </th>

            <th scope="col">
                Issued Date
            </th>

            <th scope="col">
                Due Date
            </th>

            <th scope="col">
                Status
            </th>
            <th scope="col">Issue/Return</th>

            <th scope="col"></th>

        </tr>
    </thead>
    <tbody>

        @foreach (var obj in Model)
        {
        <tr>
            <td width="50%">@obj.BookName</td>
            <td width="30%">@obj.AuthorName</td>
            <td width="30%">@obj.ISBN</td>
            <td width="30%">@obj.IssuedStudentId</td>
            <td width="30%">@obj.IssueDate</td>
            <td width="30%">@obj.DueDate</td>
            @if (obj.Issued)
            {
                <td width="30%">Issued</td>
            }
            else
            {
                <td width="30%">Available</td>
            }

            <td class="text-center">

                <div class="w-75 btn-group " role="group">

                    <a class="btn btn-primary " onclick="showInPopup('Book/Issue/@obj.Id.ToString()', 'Issue Book')"><i class="fas fa-plus"></i> Issue</a>
                    <a asp-route-Id="@obj.Id" asp-action="Return" class="btn btn-danger mx-1"><i class="far fa-edit"></i>  Return</a>

                </div>
            </td>

            <td class="text-center">

                <div class="w-75 btn-group " role="group">
                    <!--<a asp-route-Id="@obj.Id" asp-action="Upsert" class="btn btn-primary mx-1"><i class="far fa-edit"></i>  Edit</a>-->



                    <a class="btn btn-primary " onclick="showInPopup('Book/Upsert/@obj.Id.ToString()', 'Edit Book')"><i class="fas fa-plus"></i> Edit</a>
                    <a onclick="showInPopup('Book/Delete/@obj.Id.ToString()', 'Delete Book')" class="btn btn-danger "><i class="far fa-trash-alt"></i>  Delete</a>

                </div>
            </td>

        </tr>
        }


    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>